snmp:
  target: "10.0.0.128"
  port: 161
  community: "private"
  version: "1"
  timeout: 5
  retries: 3
  repeatEverySecond: 5

oids:
  #  - oid: "1.3.6.1.4.1.935.10.1.1"     # all  upsE
  - oid: "1.3.6.1.4.1.935.10.1.1.1"    # upsEIdentity
  - oid: "1.3.6.1.4.1.935.10.1.1.2"    # upsESystemSummary
  - oid: "1.3.6.1.4.1.935.10.1.1.3"    # upsEBatterySystem
