{
 "title": "UPS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UPS firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEIdentityUPSFirmwareVerison\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsESystemStatus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "UPS Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEIdentityModel\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Input Volts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEBatteryEstimatedChargeRemaining\" or r[\"_field\"] == \"upsEPositiveBatteryVoltage\" or r[\"_field\"] == \"upsESystemInputVoltage\" or r[\"_field\"] == \"upsESystemOutputLoad\" or r[\"_field\"] == \"upsESystemOutputVoltage\") \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsESystemInputVoltage\" then float(v: r._value) / 10.0 \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Output Hz",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsESystemOutputFrequency\" ) \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsESystemOutputFrequency\" then float(v: r._value) / 10.0\r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synoSystem",
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsESystemOutputLoad\" ) \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsESystemOutputLoad\" then float(v: r._value) \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "upsBatteryCharge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synoSystem",
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEBatteryEstimatedChargeRemaining\" or r[\"_field\"] == \"upsEPositiveBatteryVoltage\" or r[\"_field\"] == \"upsESystemInputVoltage\" or r[\"_field\"] == \"upsESystemOutputLoad\" or r[\"_field\"] == \"upsESystemOutputVoltage\") \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsEPositiveBatteryVoltage\" then float(v: r._value) / 10.0 \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "upsBatteryCharge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synoSystem",
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEBatteryEstimatedChargeRemaining\" ) \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsEBatteryEstimatedChargeRemaining\" then float(v: r._value) \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "upsBatteryCharge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synoSystem",
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsESystemTemperature\" ) \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsESystemTemperature\" then float(v: r._value) / 10.0 \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "upsBatteryCharge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Module firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEIdentityAgentSoftwareVerison\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEBatteryStatus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Output Volts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsESystemOutputVoltage\") \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsESystemOutputVoltage\" then float(v: r._value) / 10.0 \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Time on battery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsESecondsOnBattery\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "bucket" },
  {
   "title": "IPPON UPS",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "synoSystem",
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEBatteryEstimatedChargeRemaining\" or r[\"_field\"] == \"upsEPositiveBatteryVoltage\" or r[\"_field\"] == \"upsESystemInputVoltage\" or r[\"_field\"] == \"upsESystemOutputLoad\" or r[\"_field\"] == \"upsESystemOutputVoltage\") \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsEPositiveBatteryVoltage\" then float(v: r._value) / 10.0 \r\n        else if r[\"_field\"] == \"upsESystemInputVoltage\" then float(v: r._value) / 10.0 \r\n        else if r[\"_field\"] == \"upsESystemOutputVoltage\" then float(v: r._value) / 10.0 \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "upsLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IPPON Temp",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "synoSystem",
     "query": "from(bucket: \"ups\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsESystemTemperature\" ) \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: \r\n        if r[\"_field\"] == \"upsESystemTemperature\" then float(v: r._value) / 10.0 \r\n        else float(v: r._value),\r\n      _field: r._field,\r\n      _measurement: r._measurement\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "upsLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}